version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "python"
        versions: ["^\\d+\\.\\d+\\.\\d+(a|b|rc)"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
