name: Docker Build/Publish Release
on:
  schedule:
  - cron:  '15 6 * * 0'
  workflow_dispatch: {}

jobs:
  build:
    uses: sfudeus/workflows/.github/workflows/docker-build-publish-branch.yaml@main
    secrets: inherit
